using System.ComponentModel.DataAnnotations;
using ViewModels.Shared;
using ViewModels.Users;
using System.ComponentModel;
using Microsoft.AspNetCore.Http;
using ViewModels.Role;
using Models.Common.Interfaces;
using ViewModels.User.interfaces;

namespace ViewModels.Employee
{
    public class EmployeeUpdateViewModel : BaseUpdateVM, IBaseCrudViewModel, IUserCreateViewModel, IUserUpdateViewModel, IIdentitifier
    {
        [Required]
        [Display(Name = "First Name")]
        [MaxLength(100)]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [MaxLength(100)]
        public string? LastName { get; set; }


        //public UserBriefViewModel AssignedTo { get; set; } = new();

        //[Display(Name = "Address Line 1")]
        //[MaxLength(1000)]
        //public string? AddressLine1 { get; set; }

        //[Display(Name = "Address Line 2")]
        //[MaxLength(1000)]
        //public string? AddressLine2 { get; set; }

        //[Display(Name = "City")]
        //[MaxLength(100)]
        //public string? City { get; set; }

        //[Display(Name = "State")]
        //[MaxLength(100)]
        //public string? State { get; set; }

        //[Display(Name = "Zip")]
        //[MaxLength(100)]
        //public string? Zip { get; set; }

        [DisplayName("Use AutoGenerated Password?")]
        public bool UseAutoGeneratedPassword { get; set; } = true;

        [DataType(DataType.Password)]
        public string? Password { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "Confirm Password Does not Match with password")]
        public string? ConfirmPassword { get; set; }
        public string? PinCode { get; set; }

        public bool ChangePassword { get; set; }
        public bool HasAdditionInfo { get; set; } 

        public long UserId { get; set; }
        public string? Email { get; set; }

        public RoleBriefViewModel Role { get; set; } = new();

        public IFormFile? File { get; set; }
        public string GetBaseFolder()
        {
            //var ext = Path.GetExtension(File.FileName);
            //if (ext == ".jpg" || ext == ".jpeg" || ext == ".png")
            //{
            //    return "Images";
            //}
            //if (ext == ".mp4")
            //{
            //    return "Videos";
            //}
            //if (ext == ".pdf" || ext == ".docx" || ext == ".xlsx" || ext == ".txt")
            //{
            //    return "Documents";
            //}
            return "Employee";
        }
    }
}
