using System.ComponentModel.DataAnnotations;
using ViewModels.Shared;
using ViewModels.Users;
using System.ComponentModel;
using Microsoft.AspNetCore.Http;
using ViewModels.Role;
using Models.Common.Interfaces;
using ViewModels.User.interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ViewModels.Technician
{
    public class TechnicianUpdateViewModel : BaseUpdateVM, IBaseCrudViewModel, IUserCreateViewModel, IUserUpdateViewModel, IIdentitifier
    {
        [Required]
        [Display(Name = "First Name")]
        [MaxLength(100)]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [MaxLength(100)]
        public string? LastName { get; set; }

        [DisplayName("Use AutoGenerated Password?")]
        public bool UseAutoGeneratedPassword { get; set; } = false;

        [DataType(DataType.Password)]
        public string? Password { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "Confirm Password Does not Match with password")]
        public string? ConfirmPassword { get; set; }

        [DisplayName("Pin Code")]
        [RegularExpression(@"^(\d{4})$", ErrorMessage = "Pin Code must be of 4-digits.")]
        [Remote(action: "ValidatePincode", controller: "Technician", AdditionalFields = "Id,PinCode", ErrorMessage = "Pin Code already in use.")]
        public string? PinCode { get; set; }
        [Required]
        [Display(Name = "Confirm Pin Code")]
        [Compare("PinCode", ErrorMessage = "Confirm Pin Code Does not Match with Access Code")]
        public string ConfirmPincode { get; set; }

        public bool ChangePassword { get; set; }
        public bool HasAdditionInfo { get; set; } 

        public long UserId { get; set; }
        public string? Email { get; set; }

        public RoleBriefViewModel Role { get; set; } = new();

        public IFormFile? File { get; set; }
        public string GetBaseFolder()
        {
            //var ext = Path.GetExtension(File.FileName);
            //if (ext == ".jpg" || ext == ".jpeg" || ext == ".png")
            //{
            //    return "Images";
            //}
            //if (ext == ".mp4")
            //{
            //    return "Videos";
            //}
            //if (ext == ".pdf" || ext == ".docx" || ext == ".xlsx" || ext == ".txt")
            //{
            //    return "Documents";
            //}
            return "Technician";
        }
    }
}
