using Helpers.File;
using ViewModels.Users;

namespace ViewModels.User.interfaces
{
    public interface IUserCreateViewModel : IEmail, IFileModel, IRole
    {
        string? Password { get; set; }
        string? ConfirmPassword { get; set; }
        bool UseAutoGeneratedPassword { get; set; }
        bool ChangePassword { get; set; }

        bool HasAdditionInfo { get; set; }

        long UserId { get; set; }
        string? PinCode { get; set; }
    }


}
